# Generated by Django 5.1.5 on 2025-01-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='profile_images/blankprofilepic.webp', upload_to='profile_images'),
        ),
    ]
